/*
 * Java domain class for entity "BranchMaster" 
 * Created on 2023-02-13 ( Date ISO 2023-02-13 - Time 15:52:50 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-02-13 ( 15:52:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.madison.motor.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.madison.motor.entity.BranchMaster;
import com.madison.motor.entity.BranchMasterId;

/**
 * <h2>BranchMasterRepository</h2>
 *
 * createdAt : 2023-02-13 - Time 15:52:50
 * <p>
 * Description: "BranchMaster" Repository
 */
 
 
@Repository 
public interface BranchMasterRepository  extends JpaRepository<BranchMaster,BranchMasterId > , JpaSpecificationExecutor<BranchMaster> {

	BranchMaster findByBranchCode(String branchCode);


	List<BranchMaster> findByStatusOrderByBranchNameAsc(String status);
}
