/*
 * Java domain class for entity "BrokerBranchMaster" 
 * Created on 2023-02-13 ( Date ISO 2023-02-13 - Time 15:52:51 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-02-13 ( 15:52:51 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.madison.motor.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.madison.motor.entity.BrokerBranchMaster;
import com.madison.motor.entity.BrokerBranchMasterId;
/**
 * <h2>BrokerBranchMasterRepository</h2>
 *
 * createdAt : 2023-02-13 - Time 15:52:51
 * <p>
 * Description: "BrokerBranchMaster" Repository
 */
 
 
 
public interface BrokerBranchMasterRepository  extends JpaRepository<BrokerBranchMaster,BrokerBranchMasterId > , JpaSpecificationExecutor<BrokerBranchMaster> {

}
