/*
 * Java domain class for entity "HomePositionMaster" 
 * Created on 2023-02-13 ( Date ISO 2023-02-13 - Time 15:54:16 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-02-13 ( 15:54:16 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.madison.motor.repository;

import java.math.BigDecimal;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.madison.motor.entity.HomePositionMaster;
import com.madison.motor.entity.HomePositionMasterId;
/**
 * <h2>HomePositionMasterRepository</h2>
 *
 * createdAt : 2023-02-13 - Time 15:54:16
 * <p>
 * Description: "HomePositionMaster" Repository
 */
 
 
 
public interface HomePositionMasterRepository  extends JpaRepository<HomePositionMaster,HomePositionMasterId > , JpaSpecificationExecutor<HomePositionMaster> {

	HomePositionMaster findByApplicationNo(BigDecimal bigDecimal);

}
