/*
 * Java domain class for entity "ListItemValue" 
 * Created on 2023-02-13 ( Date ISO 2023-02-13 - Time 15:54:35 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-02-13 ( 15:54:35 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.madison.motor.repository;

import java.util.List;
import java.util.Map;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

import com.madison.motor.entity.ListItemValue;
import com.madison.motor.entity.ListItemValueId;
/**
 * <h2>ListItemValueRepository</h2>
 *
 * createdAt : 2023-02-13 - Time 15:54:35
 * <p>
 * Description: "ListItemValue" Repository
 */
 
 
 
public interface ListItemValueRepository  extends JpaRepository<ListItemValue,ListItemValueId > , JpaSpecificationExecutor<ListItemValue> {

	List<ListItemValue> findByItemTypeIgnoreCaseAndStatusIgnoreCase(String itemType, String status);
	
	@Query(value="SELECT branch_code, branch_name FROM branch_master WHERE branch_code IN( SELECT DISTINCT( regexp_substr(lc_login, '[^,]+', 1, level)) lc_login FROM ( SELECT attached_branch lc_login FROM login_master WHERE login_id =?1) b CONNECT BY level <= length(lc_login) - length(replace(lc_login, ',', '')) + 1 AND lc_login IS NOT NULL ) AND status = 'Y'",nativeQuery=true)
	List<Map<String,Object>>getBranchByLoginId(String loginId);
}
