/*
 * Java domain class for entity "MotorDataDetail" 
 * Created on 2023-02-13 ( Date ISO 2023-02-13 - Time 15:55:36 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-02-13 ( 15:55:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.madison.motor.repository;

import java.math.BigDecimal;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.madison.motor.entity.MotorDataDetail;
import com.madison.motor.entity.MotorDataDetailId;
/**
 * <h2>MotorDataDetailRepository</h2>
 *
 * createdAt : 2023-02-13 - Time 15:55:36
 * <p>
 * Description: "MotorDataDetail" Repository
 */
 
 
 
public interface MotorDataDetailRepository  extends JpaRepository<MotorDataDetail,MotorDataDetailId > , JpaSpecificationExecutor<MotorDataDetail> {

	MotorDataDetail findByApplicationNoAndVehicleId(BigDecimal applicatioNo, BigDecimal vehicleId);

}
