/*
 * Java domain class for entity "MotorPolicytypeMaster" 
 * Created on 2023-02-13 ( Date ISO 2023-02-13 - Time 15:56:56 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-02-13 ( 15:56:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.madison.motor.repository;

import java.math.BigDecimal;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.madison.motor.entity.MotorPolicytypeMaster;
/**
 * <h2>MotorPolicytypeMasterRepository</h2>
 *
 * createdAt : 2023-02-13 - Time 15:56:56
 * <p>
 * Description: "MotorPolicytypeMaster" Repository
 */
 
 
 
public interface MotorPolicytypeMasterRepository  extends JpaRepository<MotorPolicytypeMaster,BigDecimal > , JpaSpecificationExecutor<MotorPolicytypeMaster> {

}
