/*
 * Java domain class for entity "MotorPolicyDetails" 
 * Created on 2023-02-13 ( Date ISO 2023-02-13 - Time 15:56:51 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-02-13 ( 15:56:51 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.madison.motor.repository;

import java.math.BigDecimal;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.madison.motor.entity.MotorPolicyDetails;
/**
 * <h2>MotorPolicyDetailsRepository</h2>
 *
 * createdAt : 2023-02-13 - Time 15:56:51
 * <p>
 * Description: "MotorPolicyDetails" Repository
 */
 
 
 
public interface MotorPolicyDetailsRepository  extends JpaRepository<MotorPolicyDetails,BigDecimal > , JpaSpecificationExecutor<MotorPolicyDetails> {

}
