/*
 * Java domain class for entity "PersonalInfo" 
 * Created on 2023-02-13 ( Date ISO 2023-02-13 - Time 15:58:59 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-02-13 ( 15:58:59 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.madison.motor.repository;

import java.math.BigDecimal;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.madison.motor.entity.PersonalInfo;
/**
 * <h2>PersonalInfoRepository</h2>
 *
 * createdAt : 2023-02-13 - Time 15:58:59
 * <p>
 * Description: "PersonalInfo" Repository
 */
 
 
 
public interface PersonalInfoRepository  extends JpaRepository<PersonalInfo,BigDecimal > , JpaSpecificationExecutor<PersonalInfo> {

}
