/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2023-02-13 ( Date ISO 2023-02-13 - Time 15:52:50 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2023-02-13 ( 15:52:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.madison.motor.entity;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "BranchMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(BranchMasterId.class)
@Table(name="BRANCH_MASTER")


public class BranchMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="BRANCH_CODE", nullable=false, length=8)
    private String     branchCode ;

    @Id
    @Column(name="AMEND_ID", nullable=false)
    private BigDecimal amendId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="SNO__")
    private BigDecimal sno ;

    @Column(name="BRANCH_NAME", length=50)
    private String     branchName ;

    @Column(name="ADDRESS1", length=75)
    private String     address1 ;

    @Column(name="ADDRESS2", length=75)
    private String     address2 ;

    @Column(name="ADDRESS3", length=75)
    private String     address3 ;

    @Column(name="CITY", length=25)
    private String     city ;

    @Column(name="COUNTRY", length=25)
    private String     country ;

    @Column(name="PHONE", length=15)
    private String     phone ;

    @Column(name="EMAIL", length=40)
    private String     email ;

    @Column(name="BELONGING_BRANCH", length=10)
    private String     belongingBranch ;

    @Column(name="CORE_APP_CODE", length=100)
    private String     coreAppCode ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DATE", nullable=false)
    private Date       effectiveDate ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="FAX")
    private BigDecimal fax ;

    @Column(name="HEADER_IMG", length=50)
    private String     headerImg ;

    @Column(name="FOOTER_IMG", length=50)
    private String     footerImg ;

    @Column(name="SIGN_IMG", length=50)
    private String     signImg ;

    @Column(name="STAMP", length=50)
    private String     stamp ;

    @Column(name="CURRENCY_NAME", length=25)
    private String     currencyName ;

    @Column(name="CURRENCY_ABBREVIATION", length=10)
    private String     currencyAbbreviation ;

    @Column(name="CURRENCY_ACRONYM", length=10)
    private String     currencyAcronym ;

    @Column(name="ORIGINATION_COUNTRY_ID")
    private BigDecimal originationCountryId ;

    @Column(name="DESTINATION_COUNTRY_ID")
    private BigDecimal destinationCountryId ;

    @Column(name="CURRENCY_DECIMAL_NAME", length=20)
    private String     currencyDecimalName ;

    @Column(name="CURRENCY_DECIMAL_DIGIT")
    private BigDecimal currencyDecimalDigit ;

    @Column(name="LANG_YN", length=1)
    private String     langYn ;

    @Column(name="DECIMAL_PLACES")
    private BigDecimal decimalPlaces ;

    @Column(name="TAX")
    private BigDecimal tax ;

    @Column(name="BRANCH_PREFIX", length=10)
    private String     branchPrefix ;

    @Column(name="PCKEY_CLOSE_TRN", length=5)
    private String     pckeyCloseTrn ;

    @Column(name="POLICY_FEE_PERCENT")
    private BigDecimal policyFeePercent ;

    @Column(name="DEPT_CODE", length=10)
    private String     deptCode ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



