/*
 * Created on 2023-02-13 ( 15:52:53 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.madison.motor.entity;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;


import java.math.BigDecimal;

/**
 * Composite primary key for entity "BrokerCommissionDetail" ( stored in table "BROKER_COMMISSION_DETAIL" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class BrokerCommissionDetailId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     agencyCode ;
    
    private String     loginId ;
    
    private BigDecimal productId ;
    
    private BigDecimal policytype ;
    
    private BigDecimal amendId ;
    
     
}
