/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2023-02-13 ( Date ISO 2023-02-13 - Time 15:52:52 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2023-02-13 ( 15:52:53 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.madison.motor.entity;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "BrokerCommissionDetail"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(BrokerCommissionDetailId.class)
@Table(name="BROKER_COMMISSION_DETAIL")


public class BrokerCommissionDetail implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="AGENCY_CODE", nullable=false, length=50)
    private String     agencyCode ;

    @Id
    @Column(name="LOGIN_ID", nullable=false, length=200)
    private String     loginId ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private BigDecimal productId ;

    @Id
    @Column(name="POLICYTYPE", nullable=false)
    private BigDecimal policytype ;

    @Id
    @Column(name="AMEND_ID", nullable=false)
    private BigDecimal amendId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="POLICY_FEE")
    private BigDecimal policyFee ;

    @Column(name="OTHER_FEE")
    private BigDecimal otherFee ;

    @Column(name="SUMINSURED_START")
    private BigDecimal suminsuredStart ;

    @Column(name="SUMINSURED_END")
    private BigDecimal suminsuredEnd ;

    @Column(name="MIN_PREMIUM")
    private BigDecimal minPremium ;

    @Column(name="COMMISSION_PERCENTAGE")
    private BigDecimal commissionPercentage ;

    @Column(name="CHECKER_YN", length=10)
    private String     checkerYn ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE")
    private Date       effectiveDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_DATE")
    private Date       endDate ;

    @Column(name="OTHER_FEE_1")
    private BigDecimal otherFee1 ;

    @Column(name="OTHER_FEE_2")
    private BigDecimal otherFee2 ;

    @Column(name="OTHER_FEE_3")
    private BigDecimal otherFee3 ;

    @Column(name="POLICYTYPE_OPTED", length=1)
    private String     policytypeOpted ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



