/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2023-02-13 ( Date ISO 2023-02-13 - Time 15:52:55 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2023-02-13 ( 15:52:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.madison.motor.entity;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import javax.persistence.*;




/**
* Domain class for entity "BrokerCompanyMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="BROKER_COMPANY_MASTER")


public class BrokerCompanyMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="AGENCY_CODE", nullable=false, length=25)
    private String     agencyCode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="COMPANY_NAME", length=75)
    private String     companyName ;

    @Column(name="CONTACT_PERSON", length=75)
    private String     contactPerson ;

    @Column(name="ADDRESS1", length=500)
    private String     address1 ;

    @Column(name="ADDRESS2", length=500)
    private String     address2 ;

    @Column(name="ADDRESS3", length=500)
    private String     address3 ;

    @Column(name="CITY", length=25)
    private String     city ;

    @Column(name="COUNTRY", length=25)
    private String     country ;

    @Column(name="PHONE", length=15)
    private String     phone ;

    @Column(name="POBOX")
    private BigDecimal pobox ;

    @Column(name="EMIRATE", length=56)
    private String     emirate ;

    @Column(name="FAX", length=50)
    private String     fax ;

    @Column(name="CUSTOMER_ID")
    private BigDecimal customerId ;

    @Column(name="BRANCH_CODE", length=8)
    private String     branchCode ;

    @Column(name="AC_EXECUTIVE_ID")
    private BigDecimal acExecutiveId ;

    @Column(name="BROKER_TYPE", length=200)
    private String     brokerType ;

    @Column(name="MISSIPPI_ID")
    private BigDecimal missippiId ;

    @Column(name="APPROVED_PREPARED_BY", length=30)
    private String     approvedPreparedBy ;

    @Column(name="RSA_BROKER_CODE", nullable=false, length=25)
    private String     rsaBrokerCode ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="SUB_BRANCH", length=8)
    private String     subBranch ;

    @Column(name="ISSUER_COMMISSION_ONEOFF")
    private BigDecimal issuerCommissionOneoff ;

    @Column(name="ISSUER_COMMISSION_OPENCOVER")
    private BigDecimal issuerCommissionOpencover ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="IMAGE_PATH", length=500)
    private String     imagePath ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



