/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2023-02-13 ( Date ISO 2023-02-13 - Time 15:54:35 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2023-02-13 ( 15:54:35 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.madison.motor.entity;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import javax.persistence.*;




/**
* Domain class for entity "ListItemValue"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(ListItemValueId.class)
@Table(name="LIST_ITEM_VALUE")


public class ListItemValue implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="ITEM_ID", nullable=false)
    private BigDecimal itemId ;

    @Id
    @Column(name="ITEM_CODE", nullable=false, length=20)
    private String     itemCode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="ITEM_TYPE", length=50)
    private String     itemType ;

    @Column(name="ITEM_VALUE", length=100)
    private String     itemValue ;

    @Column(name="ITEM_DESC", length=4000)
    private String     itemDesc ;

    @Column(name="PARAM1", length=100)
    private String     param1 ;

    @Column(name="PARAM2", length=100)
    private String     param2 ;

    @Column(name="STATUS", length=5)
    private String     status ;

    @Column(name="CORE_APP_CODE", length=100)
    private String     coreAppCode ;

    @Column(name="PACKAGE_DESC", length=500)
    private String     packageDesc ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



