/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2023-02-13 ( Date ISO 2023-02-13 - Time 15:56:51 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2023-02-13 ( 15:56:51 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.madison.motor.entity;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "MotorPolicyDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="MOTOR_POLICY_DETAILS")


public class MotorPolicyDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="APPLICATIONNO", nullable=false)
    private BigDecimal applicationno ;

    //--- ENTITY DATA FIELDS 
    @Column(name="QUOTENO")
    private BigDecimal quoteno ;

    @Column(name="POLICYTYPE")
    private BigDecimal policytype ;

    @Column(name="ISSELECTCOVER")
    private BigDecimal isselectcover ;

    @Column(name="OPTIONAL_COVER", length=200)
    private String     optionalCover ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="POLICYSTARTDATE")
    private Date       policystartdate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="POLICYENDDATE")
    private Date       policyenddate ;

    @Column(name="PREMIUM")
    private BigDecimal premium ;

    @Column(name="REFERRAL_REMARKS", length=500)
    private String     referralRemarks ;

    @Column(name="CURRENCY_TYPE", length=10)
    private String     currencyType ;

    @Column(name="LIABILITY_SI")
    private BigDecimal liabilitySi ;

    @Column(name="LIABILITY_YN", length=10)
    private String     liabilityYn ;

    @Column(name="LIABILITY_SI_USD")
    private BigDecimal liabilitySiUsd ;

    @Column(name="CONDITIONS_CLAUSES1", length=4000)
    private String     conditionsClauses1 ;

    @Column(name="CONDITIONS_CLAUSES2", length=4000)
    private String     conditionsClauses2 ;

    @Column(name="CONDITIONS_CLAUSES3", length=4000)
    private String     conditionsClauses3 ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



